export const RECENT_TRANSACTIONS = [
  {
    id: 1,
    description: 'Grocery Shopping',
    category: 'Food',
    amount: -120.5,
    date: '2023-06-15',
    account: 'Main Account',
  },
  {
    id: 2,
    description: 'Salary',
    category: 'Income',
    amount: 3500.0,
    date: '2023-06-10',
    account: 'Main Account',
  },
  {
    id: 3,
    description: 'Netflix Subscription',
    category: 'Entertainment',
    amount: -15.99,
    date: '2023-06-08',
    account: 'Credit Card',
  },
  {
    id: 4,
    description: 'Freelance Work',
    category: 'Income',
    amount: 850.0,
    date: '2023-06-05',
    account: 'Savings',
  },
  {
    id: 5,
    description: 'Restaurant',
    category: 'Food',
    amount: -65.3,
    date: '2023-06-03',
    account: 'Credit Card',
  },
]
