import { Account, Bank } from '@/lib/sdk-types'

export const BANKS_MOCK: Bank[] = [
  {
    id: 1,
    name: 'Banco de América',
    country: 'Estados Unidos',
    currency: 'USD',
    logo: '/no-image.png?height=40&width=40',
  },
  {
    id: 2,
    name: 'HSBC',
    country: 'Reino Unido',
    currency: 'GBP',
    logo: '/no-image.png?height=40&width=40',
  },
  {
    id: 3,
    name: 'Santander',
    country: 'España',
    currency: 'EUR',
    logo: '/no-image.png?height=40&width=40',
  },
  {
    id: 4,
    name: 'Deutsche Bank',
    country: 'Alemania',
    currency: 'EUR',
    logo: '/no-image.png?height=40&width=40',
  },
  {
    id: 5,
    name: 'Citibank',
    country: 'Estados Unidos',
    currency: 'USD',
    logo: '/no-image.png?height=40&width=40',
  },
]

export const ACCOUNTS_MOCK: Account[] = [
  {
    id: 1,
    bankId: 1,
    name: 'Cuenta Corriente Principal',
    accountNumber: '****4567',
    type: 'Corriente',
    balance: 3500.75,
    currency: 'USD',
  },
  {
    id: 2,
    bankId: 1,
    name: 'Cuenta de Ahorro',
    accountNumber: '****7890',
    type: 'Ahorro',
    balance: 12500.5,
    currency: 'USD',
  },
  {
    id: 3,
    bankId: 2,
    name: 'Cuenta HSBC',
    accountNumber: '****2345',
    type: 'Corriente',
    balance: 2800.3,
    currency: 'GBP',
  },
  {
    id: 4,
    bankId: 3,
    name: 'Ahorro Santander',
    accountNumber: '****8901',
    type: 'Ahorro',
    balance: 9500.0,
    currency: 'EUR',
  },
  {
    id: 5,
    bankId: 4,
    name: 'Inversión Deutsche',
    accountNumber: '****3456',
    type: 'Inversión',
    balance: 35000.0,
    currency: 'EUR',
  },
  {
    id: 6,
    bankId: 5,
    name: 'Cuenta Citibank',
    accountNumber: '****6789',
    type: 'Corriente',
    balance: 4200.25,
    currency: 'USD',
  },
  {
    id: 7,
    bankId: 5,
    name: 'Ahorro Citibank',
    accountNumber: '****0123',
    type: 'Ahorro',
    balance: 15800.75,
    currency: 'USD',
  },
]
